[package]
name = "rocker"
version = "0.1.0"
authors = ["Antoine Busch <abusch@atlassian.com>"]

[[bin]]
bench = false
path = "src/main.rs"
name = "rkr"

[dependencies]
failure = "0.1"
humantime = "1.1"
shiplift = "0.3"
termion = "*"
tui = "0.2"
